### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Michailpt** [ClemCa/python-prev#1] opened 2024-11-14 12:53 UTC
Hello, please tell me how to solve this problem, an error appears on the second line.
class Point:
def __init__(self, a: int, b: int): # syntax error: invalid syntax
self.x = a
self.y = b
pt = Point(10,30)
print (pt.x)

**Comment by ClemCa** [comment] 2024-11-14 12:57
Hi, it's likely to be a bug in the extension.
In order to keep track of what happens in the code, the extension generates python code with print statements nearly every line. There might be an issue in the generated code.
I'll take a look at it soon.

**Comment by ClemCa** [comment] 2024-11-14 16:22
Hey!
The bug has been fixed along a few others in the latest patch @Michailpt

**Comment by Michailpt** [comment] 2024-11-14 16:38
def key_sort(x):
    return x + 1 #  Comments. Syntax Error: invalid syntax
key_sort(1)

**Comment by ClemCa** [comment] 2024-11-14 16:41
> def key_sort(x): return x + 1 # Comments. Syntax Error: invalid syntax key_sort(1)

I couldn't reproduce this. Are you sure your version is up to date?

**Comment by Michailpt** [comment] 2024-11-14 16:55
Yes, the current version. Here's another one
x = 10
while x < 5:
    try:
        x = 1
        if x == 4:
            break
    except ValueError: #  Syntax Error: invalid syntax
        print(-1)
        continue

**Comment by Michailpt** [comment] 2024-11-14 17:04
Yes, the current version. Here's another one
```python
x = 10
while x < 5:
    try:
        x = 1
        if x == 4:
            break
    except ValueError: #  SyntaxError: expected 'except' or 'finally'
        print(-1)
        continue

**Comment by ClemCa** [comment] 2024-11-15 12:57
I'm opening the issue back to check it out later.
The first example was not reproducible, so it was unlikely to come from this part of the code at least.
For the second example, try/except/finally does seem like an oversight in the current version.

**Comment by ClemCa** [comment] 2024-11-15 16:19
The latest patch should fix your second issue. As for you first, I just figured out I couldn't reproduce it because the importance of the comment being there wasn't highlighted.
This will be fixed today.

**Comment by ClemCa** [comment] 2024-11-15 16:22
The last issue is fixed. I'm going to close this on this note.
Should you encounter any other bug, please open a new issue to make it easier to keep track of @Michailpt

**Closed as completed by ClemCa** 2024-11-15 16:22 UTC
Labels: bug

**Comment by Michailpt** [comment] 2024-11-15 16:28
Thank you
